// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo5hHn-ZfnXkZAln4g0KSawLz_qUylu2k',
    appId: '1:982311118617:web:8a05f04400d4d6375ec788',
    messagingSenderId: '982311118617',
    projectId: 'booqui-aaea4',
    authDomain: 'booqui-aaea4.firebaseapp.com',
    storageBucket: 'booqui-aaea4.appspot.com',
    measurementId: 'G-8C3XQLG5Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANg4H5GQXXEZyceZoXFbRJssDdXa-trZY',
    appId: '1:982311118617:android:f57a6d7dd22586505ec788',
    messagingSenderId: '982311118617',
    projectId: 'booqui-aaea4',
    storageBucket: 'booqui-aaea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6b9V378pc6RI5dqNSPBkKOR2pEYgFAK4',
    appId: '1:982311118617:ios:cc494fdfff6376805ec788',
    messagingSenderId: '982311118617',
    projectId: 'booqui-aaea4',
    storageBucket: 'booqui-aaea4.appspot.com',
    iosClientId: '982311118617-qkv3m94udalqormg6h82fcfo9mbk5gbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.booqui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6b9V378pc6RI5dqNSPBkKOR2pEYgFAK4',
    appId: '1:982311118617:ios:cc494fdfff6376805ec788',
    messagingSenderId: '982311118617',
    projectId: 'booqui-aaea4',
    storageBucket: 'booqui-aaea4.appspot.com',
    iosClientId: '982311118617-qkv3m94udalqormg6h82fcfo9mbk5gbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.booqui',
  );
}
